version: '3.4'

services:
    guilhermerocha.api:
        image: ${DOCKER_REGISTRY-}guilhermerochaapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - 5000:5000
          - 5001:5001
        # depends_on:
          # - db
    # db:
        # image: mcr.microsoft.com/mssql/server:2019-latest
        # environment:
          # - SA_PASSWORD=Your_password123
          # - ACCEPT_EULA=Y
        # volumes:
          # - sqlvolume:/var/opt/mssql

# volumes:
  # sqlvolume: